apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: test-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtaptestlzhuang/test-go:535076d25e9164ba9be11a7dbfe0ed26f22c54d0
          name: container-image
